Rename scantype-configMap.yml to scantype-configMap.yaml
Small mistake in naming the file. The integration tests expect a .yaml file (not .yml)
```
Run kubectl -n integration-tests delete scans --all
scan.execution.***.io "invalid-findings-test-scan-xnb9l" deleted
scan.execution.***.io "scan-type-not-found-wp9zv" deleted
NAME: zap-advanced
LAST DEPLOYED: Tue Mar  1 02:47:35 2022
NAMESPACE: integration-tests
STATUS: deployed
REVISION: 1
TEST SUITE: None
error: the path "./scanners/zap-advanced/integration-tests/scantype-configMap.yaml" does not exist
```

Signed-off-by: Rami Souai <rami.souai@iteratec.com>