Switching security context privileges to root privileges
This is necessary because the provided amass container has a non-numeric user that cannot be verified to be root or not:
Error: container has runAsNonRoot and image has non-numeric user (user), cannot verify user is non-root (pod: "scan-amass-scanner-dummy-scan, container: amass)

Signed-off-by: Sebastian <sebastian.franz@iteratec.com>